from utils.custom_exception import FtzException


class ExternalUserCreateException(FtzException):
    pass
